# Splunk ulimits — Splunk requires high nofile + nproc.
# See https://docs.splunk.com/Documentation/Splunk/latest/Installation/Systemrequirements
splunk hard core      0
splunk hard maxlogins 10
splunk hard nofile    64000
splunk soft nofile    64000
splunk hard nproc     16000
splunk soft nproc     16000
splunk hard data      1073741824
splunk soft data      1073741824
splunk hard fsize     -1
splunk soft fsize     -1
